# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('bank_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('logo', models.URLField(max_length=256)),
                ('city', models.CharField(choices=[(b'Ahemdabad', b'Ahemdabad'), (b'Jaipur', b'Jaipur'), (b'Mumbai', b'Mumbai'), (b'Pune', b'Pune')], max_length=64)),
                ('reg_no', models.IntegerField(blank=True, null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('A_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('A_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('B_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('B_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('AB_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('AB_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('O_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('O_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('Ffp', models.IntegerField(blank=True, default=0, null=True)),
                ('Plt', models.IntegerField(blank=True, default=0, null=True)),
                ('Cry', models.IntegerField(blank=True, default=0, null=True)),
                ('Lpl', models.IntegerField(blank=True, default=0, null=True)),
                ('Aph', models.IntegerField(blank=True, default=0, null=True)),
                ('Unt', models.IntegerField(blank=True, default=0, null=True)),
                ('Ca_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('Ca_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('Cb_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('Cb_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('Cab_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('Cab_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('Co_plus', models.IntegerField(blank=True, default=0, null=True)),
                ('Co_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile_no', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
