# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-12 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20160812_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_bank',
            name='city',
            field=models.CharField(choices=[(b'Bhopal', b'Bhopal'), (b'Indore', b'Indore')], max_length=64),
        ),
    ]
